package com.svoemesto.karaokeweb.dto

import com.svoemesto.karaokeapp.model.Settings

data class SettingsPublicDto(
    val id: Long,
    val songName: String,
    val author: String,
    val album: String,
    val year: Long,
    val track: Long,
    val key: String,
    val bpm: Long,
    val onAir: Boolean,
    val exclusive: Boolean,
    val datePublish: String,
    val airTimestamp: Long?,
    val sponsrLinkGeneral: String,
    val haveVkGroupLink: Boolean,
    val idStatus: Long,
    val vkPictureBase64: String,
    val songPictureUrl: String,
    val formattedTextSong: String,
    val formattedTextTabs: String,
    val formattedTextChords: String,
    val linkSponsrPlay: String,
    val linkBoostyTxt: String,
    val linkDzenKaraoke: String,
    val linkDzenLyrics: String,
    val linkDzenTabs: String,
    val linkDzenChords: String,
    val linkVkKaraoke: String,
    val linkVkLyrics: String,
    val linkVkTabs: String,
    val linkVkChords: String,
    val linkTgKaraoke: String,
    val linkTgLyrics: String,
    val linkTgTabs: String,
    val linkTgChords: String,
    val linkMaxKaraoke: String,
    val linkMaxLyrics: String,
    val linkMaxTabs: String,
    val linkMaxChords: String,
    val linkPlKaraoke: String,
    val linkPlLyrics: String,
    val linkPlTabs: String,
    val linkPlChords: String,
    val idVkKaraoke: String,
    val idVkKaraokeOID: String,
    val idVkKaraokeID: String,
    val idVkLyrics: String,
    val idVkLyricsOID: String,
    val idVkLyricsID: String,
    val idVkMelody: String,
    val idVkMelodyOID: String,
    val idVkMelodyID: String,
    val idVkChords: String,
    val idVkChordsOID: String,
    val idVkChordsID: String,
    val contentRemoved: Boolean,
    // Доступна ли отдельная подписка на эту песню (id_tariff: 0 по умолчанию = разрешено тарифом
    // по умолчанию; -1 = автор запретил в карточке песни, webvue3). Без is-префикса — иначе Jackson
    // съел бы его в JSON-ключе (инвариант проекта).
    val songSubscriptionAvailable: Boolean,
) {
    companion object {
        /**
         * includeDetails=false пропускает getVKPictureBase64()/formattedText* — это тяжёлые поля,
         * нужные только на странице одной песни. Список/поиск их не показывали и в старых шаблонах
         * (filter.html/zakroma.html), а getVKPictureBase64() может полезть в rootFolder-фоллбек
         * karaoke-app (Constants.PROJECT_ROOT_FOLDERS), который требует APP_WORK_ON_SERVER —
         * а её в процессе karaoke-web никто не инициализирует (KaraokeAppService там не поднимается).
         */
        fun fromSettings(s: Settings, includeDetails: Boolean = true): SettingsPublicDto = SettingsPublicDto(
            id = s.id,
            songName = s.songName,
            author = s.author,
            album = s.album,
            year = s.year,
            track = s.track,
            key = s.key,
            bpm = s.bpm,
            onAir = s.onAir,
            exclusive = s.exclusive,
            datePublish = s.datePublish,
            airTimestamp = s.dateTimePublish?.time,
            sponsrLinkGeneral = "https://sponsr.ru/smkaraoke",
            haveVkGroupLink = s.haveVkGroupLink,
            idStatus = s.idStatus,
            vkPictureBase64 = "",
            songPictureUrl = "/api/public/song-picture/${s.id}",
            formattedTextSong = if (includeDetails) s.formattedTextSong else "",
            formattedTextTabs = if (includeDetails) s.formattedTextTabs else "",
            formattedTextChords = if (includeDetails) s.formattedTextChords else "",
            linkSponsrPlay = s.linkSponsrPlay,
            linkBoostyTxt = s.linkBoostyTxt,
            linkDzenKaraoke = s.linkDzenKaraoke,
            linkDzenLyrics = s.linkDzenLyrics,
            linkDzenTabs = s.linkDzenTabs,
            linkDzenChords = s.linkDzenChords,
            linkVkKaraoke = s.linkVkKaraoke,
            linkVkLyrics = s.linkVkLyrics,
            linkVkTabs = s.linkVkTabs,
            linkVkChords = s.linkVkChords,
            linkTgKaraoke = s.linkTgKaraoke,
            linkTgLyrics = s.linkTgLyrics,
            linkTgTabs = s.linkTgTabs,
            linkTgChords = s.linkTgChords,
            linkMaxKaraoke = s.linkMaxKaraoke,
            linkMaxLyrics = s.linkMaxLyrics,
            linkMaxTabs = s.linkMaxTabs,
            linkMaxChords = s.linkMaxChords,
            linkPlKaraoke = s.linkPlKaraoke,
            linkPlLyrics = s.linkPlLyrics,
            linkPlTabs = s.linkPlTabs,
            linkPlChords = s.linkPlChords,
            idVkKaraoke = s.idVkKaraoke,
            idVkKaraokeOID = s.idVkKaraokeOID,
            idVkKaraokeID = s.idVkKaraokeID,
            idVkLyrics = s.idVkLyrics,
            idVkLyricsOID = s.idVkLyricsOID,
            idVkLyricsID = s.idVkLyricsID,
            idVkMelody = s.idVkMelody,
            idVkMelodyOID = s.idVkMelodyOID,
            idVkMelodyID = s.idVkMelodyID,
            idVkChords = s.idVkChords,
            idVkChordsOID = s.idVkChordsOID,
            idVkChordsID = s.idVkChordsID,
            contentRemoved = s.tags.split(" ").map { it.uppercase() }.contains("SKIP"),
            songSubscriptionAvailable = s.idTariff >= 0,
        )
    }
}
