version: "3.9"
services:
  karaoke-db:
    image: postgres:16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "karaoke"
      PGDATA: "/var/lib/postgresql/data/16"
      WORK_IN_CONTAINER: 1
    container_name: karaoke-db
    ports:
      - "8832:5432" # порт хоста : порт внутри контейнера
    networks:
      - karaokenet
    volumes: # локальная папка : папка внутри контейнера
      - /sm-karaoke/system/Караоке-db:/var/lib/postgresql/data/16 # мапим локальную папку /sm-karaoke/system/Караоке-db в контейнер по пути /var/lib/postgresql/data/16
      - /sm-karaoke/system/dumps:/dumps # мапим папку /sm-karaoke/system/dumps в контейнер по пути /dumps
    restart: always

networks:
  karaokenet:
    external: true # <-- Указываем, что сеть внешняя
