version: "3.9"
services:

  karaoke-app:
    container_name: karaoke-app
    image: svoemestodev/karaoke-app:1
    ports:
      - "8898:8899"
    environment:
      - WORK_IN_CONTAINER=1
      - STORAGE_FOLDER=${STORAGE_FOLDER}
      - STORAGE_PORT_HOST=${STORAGE_PORT_HOST}
      - STORAGE_PORT_INSIDE_CONTAINER=${STORAGE_PORT_INSIDE_CONTAINER}
      - STORAGE_CONSOLE_PORT_HOST=${STORAGE_CONSOLE_PORT_HOST}
      - STORAGE_CONSOLE_PORT_INSIDE_CONTAINER=${STORAGE_CONSOLE_PORT_INSIDE_CONTAINER}
      - STORAGE_CONTAINER_NAME=${STORAGE_CONTAINER_NAME}
      - STORAGE_KEY=${STORAGE_KEY}
      - STORAGE_SECRET=${STORAGE_SECRET}
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - /sm-karaoke/work:/sm-karaoke/work
      - /sm-karaoke/done1:/sm-karaoke/done1
      - /sm-karaoke/done2:/sm-karaoke/done2
      - /sm-karaoke/system:/sm-karaoke/system
      - /sm-karaoke/store:/sm-karaoke/store
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/nsa/Karaoke/karaoke-web/src/main/resources/static/tmp:/home/nsa/Karaoke/karaoke-web/src/main/resources/static/tmp
    networks:
      - karaokenet # Используем внешнюю сеть
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu", "utility", "compute", "video"]
    entrypoint:
      - java
      - -Xmx2g
    command: -jar /app.jar

networks:
  karaokenet:
    external: true # <-- Указываем, что сеть внешняя
