version: "3.9"
services:

  karaoke-app:
    container_name: karaoke-app
    image: svoemestodev/karaoke-app:1
    ports:
      - "8898:8899"
    environment:
      WORK_IN_CONTAINER: 1
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    volumes:
      - /sm-karaoke/work:/sm-karaoke/work
      - /sm-karaoke/done1:/sm-karaoke/done1
      - /sm-karaoke/done2:/sm-karaoke/done2
      - /sm-karaoke/system:/sm-karaoke/system
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/nsa/Karaoke/karaoke-web/src/main/resources/static/tmp:/home/nsa/Karaoke/karaoke-web/src/main/resources/static/tmp
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Xmx2g
    command: -jar /app.jar

networks:
  karaokenet:
    driver: bridge
