version: '3.8'

services:
  mlt:
    container_name: melt
    image: svoemestodev/melt:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /sm-karaoke/work:/sm-karaoke/work
      - /sm-karaoke/done1:/sm-karaoke/done1
      - /sm-karaoke/done2:/sm-karaoke/done2
      - /sm-karaoke/system:/sm-karaoke/system
    working_dir: /app
    command: ["-progress", "/sm-karaoke/work/test.mlt"]
