version: "3.9"
services:

  karaoke-app:
    container_name: karaoke-app
    image: ${DOCKER_REGISTRY}/karaoke-app:${BUILD_VERSION}
    ports:
      - ${APP_PORT_HOST}:${APP_PORT_INSIDE_CONTAINER}
    environment:
      - WORK_IN_CONTAINER=1
      - STORAGE_FOLDER=${STORAGE_FOLDER}
      - STORAGE_PORT_HOST=${STORAGE_PORT_HOST}
      - STORAGE_PORT_INSIDE_CONTAINER=${STORAGE_PORT_INSIDE_CONTAINER}
      - STORAGE_CONSOLE_PORT_HOST=${STORAGE_CONSOLE_PORT_HOST}
      - STORAGE_CONSOLE_PORT_INSIDE_CONTAINER=${STORAGE_CONSOLE_PORT_INSIDE_CONTAINER}
      - STORAGE_CONTAINER_NAME=${STORAGE_CONTAINER_NAME}
      - STORAGE_KEY=${STORAGE_KEY}
      - STORAGE_SECRET=${STORAGE_SECRET}
    volumes:
      - ${APP_FOLDER_HOST}:${APP_FOLDER_IN_CONTAINER}
      - ${APP_FOLDER_K1}:${APP_FOLDER_K1}
      - ${APP_FOLDER_K2}:${APP_FOLDER_K2}
      - ${APP_FOLDER_K3}:${APP_FOLDER_K3}
      - ${APP_FOLDER_SYSTEM}:${APP_FOLDER_SYSTEM}
      - ${APP_FOLDER_STORE}:${APP_FOLDER_STORE}
    networks:
      - karaokenet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu", "utility", "compute", "video"]
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
    command: ${APP_JAVA_OPTS} -jar /app.jar

networks:
  karaokenet:
    driver: bridge

