version: "3.9"
services:

  karaoke-webvue:
    container_name: karaoke-webvue
    image: ${DOCKER_REGISTRY}/karaoke-webvue:${BUILD_VERSION}
    ports:
      - "7905:7905"
    volumes:
      - ${APP_FOLDER_HOST}:${APP_FOLDER_IN_CONTAINER}
      - ${APP_FOLDER_K1}:${APP_FOLDER_K1}
      - ${APP_FOLDER_K2}:${APP_FOLDER_K2}
      - ${APP_FOLDER_K3}:${APP_FOLDER_K3}
      - ${APP_FOLDER_SYSTEM}:${APP_FOLDER_SYSTEM}
      - ${WEBVUE_PATH_TO_NGINX_CONF}:/etc/nginx/nginx.conf
    networks:
      - karaokenet
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

networks:
  karaokenet:
    external: true # <-- Указываем, что сеть внешняя

