version: "3.9"
services:

  karaoke-app:
    container_name: karaoke-app
    image: ${DOCKER_REGISTRY}/karaoke-app:${BUILD_VERSION}
    ports:
      - ${APP_PORT_HOST}:${APP_PORT_INSIDE_CONTAINER}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - LANG=C.utf8
      - LC_ALL=C.utf8
      - WORK_IN_CONTAINER=1
      - STORAGE_FOLDER=${STORAGE_FOLDER}
      - STORAGE_PORT_HOST=${STORAGE_PORT_HOST}
      - STORAGE_PORT_INSIDE_CONTAINER=${STORAGE_PORT_INSIDE_CONTAINER}
      - STORAGE_CONSOLE_PORT_HOST=${STORAGE_CONSOLE_PORT_HOST}
      - STORAGE_CONSOLE_PORT_INSIDE_CONTAINER=${STORAGE_CONSOLE_PORT_INSIDE_CONTAINER}
      - STORAGE_CONTAINER_NAME=${STORAGE_CONTAINER_NAME}
      - STORAGE_KEY=${STORAGE_KEY}
      - STORAGE_SECRET=${STORAGE_SECRET}
      - DB_LOCAL_POSTGRES_USER=${DB_LOCAL_POSTGRES_USER}
      - DB_LOCAL_POSTGRES_PASSWORD=${DB_LOCAL_POSTGRES_PASSWORD}
      - DB_SERVER_POSTGRES_USER=${DB_SERVER_POSTGRES_USER}
      - DB_SERVER_POSTGRES_PASSWORD=${DB_SERVER_POSTGRES_PASSWORD}
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/.Xauthority
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - SEARXNG_BASE_URL=http://searxng:8080
    volumes:
      - ${APP_FOLDER_HOST}:${APP_FOLDER_IN_CONTAINER}
      - ${APP_FOLDER_K1}:${APP_FOLDER_K1}
      - ${APP_FOLDER_K2}:${APP_FOLDER_K2}
      - ${APP_FOLDER_K3}:${APP_FOLDER_K3}
      - ${APP_FOLDER_SYSTEM}:${APP_FOLDER_SYSTEM}
      - ${APP_FOLDER_STORE}:${APP_FOLDER_STORE}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
    command: ${APP_JAVA_OPTS} -jar /app.jar

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8888:8080"
    volumes:
      - ./searxng-settings:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080/
      - SEARXNG_SECRET=i-love-my-wife-oxana
    restart: unless-stopped
    networks:
      - karaokenet

networks:
  karaokenet:
    external: true # <-- Указываем, что сеть внешняя

