version: "3.9"
services:

  karaoke-app:
    container_name: karaoke-app
    image: ${DOCKER_REGISTRY}/karaoke-app:${BUILD_VERSION}
    ports:
      - ${APP_PORT_HOST}:${APP_PORT_INSIDE_CONTAINER}
    environment:
      WORK_IN_CONTAINER: 1
    volumes:
      - ${APP_FOLDER_HOST}:${APP_FOLDER_IN_CONTAINER}
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=/dumps
    command: ${APP_JAVA_OPTS} -jar /app.jar
    restart: always

  karaoke-web:
    container_name: karaoke-web
    image: ${DOCKER_REGISTRY}/karaoke-web:${BUILD_VERSION}
    ports:
      - ${WEB_PORT_HOST}:${WEB_PORT_INSIDE_CONTAINER}
    environment:
      WORK_IN_CONTAINER: 1
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=/dumps
    command: ${APP_JAVA_OPTS} -jar /app.jar
    restart: always

networks:
  karaokenet:
    driver: bridge
