version: "3.9"
services:

  karaoke-app:
    container_name: karaoke-app
    image: ${DOCKER_REGISTRY}/karaoke-app:${BUILD_VERSION}
    ports:
      - ${APP_PORT_HOST}:${APP_PORT_INSIDE_CONTAINER}
    environment:
      WORK_IN_CONTAINER: 1
    volumes:
      - ${APP_FOLDER_HOST}:${APP_FOLDER_IN_CONTAINER}
      - ${APP_FOLDER_K1}:${APP_FOLDER_K1}
      - ${APP_FOLDER_K2}:${APP_FOLDER_K2}
      - ${APP_FOLDER_K3}:${APP_FOLDER_K3}
      - ${APP_FOLDER_SYSTEM}:${APP_FOLDER_SYSTEM}
      - ${APP_FOLDER_STORE}:${APP_FOLDER_STORE}
    networks:
      - karaokenet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu", "utility", "compute", "video"]
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
    command: ${APP_JAVA_OPTS} -jar /app.jar

  karaoke-web:
    container_name: karaoke-web
    image: ${DOCKER_REGISTRY}/karaoke-web:${BUILD_VERSION}
    ports:
      - ${WEB_PORT_HOST}:${WEB_PORT_INSIDE_CONTAINER}
    environment:
      WORK_IN_CONTAINER: 1
#    volumes:
#      - ${WEB_FOLDER_HOST}:${WEB_FOLDER_IN_CONTAINER}
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=/dumps
    command: ${APP_JAVA_OPTS} -jar /app.jar
    restart: always

  karaoke-webvue:
    container_name: karaoke-webvue
    image: ${DOCKER_REGISTRY}/karaoke-webvue:${BUILD_VERSION}
    ports:
      - "7905:7905"
    depends_on:
      - karaoke-app
    volumes:
      - ${APP_FOLDER_HOST}:${APP_FOLDER_IN_CONTAINER}
      - ${APP_FOLDER_K1}:${APP_FOLDER_K1}
      - ${APP_FOLDER_K2}:${APP_FOLDER_K2}
      - ${APP_FOLDER_K3}:${APP_FOLDER_K3}
      - ${APP_FOLDER_SYSTEM}:${APP_FOLDER_SYSTEM}
      - ${WEBVUE_PATH_TO_NGINX_CONF}:/etc/nginx/nginx.conf
    networks:
      - karaokenet
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

  karaoke-webvue3:
    container_name: karaoke-webvue3
    image: ${DOCKER_REGISTRY}/karaoke-webvue3:${BUILD_VERSION}
    ports:
      - "7906:7906"
    depends_on:
      - karaoke-app
    volumes:
      - ${APP_FOLDER_HOST}:${APP_FOLDER_IN_CONTAINER}
      - ${APP_FOLDER_K1}:${APP_FOLDER_K1}
      - ${APP_FOLDER_K2}:${APP_FOLDER_K2}
      - ${APP_FOLDER_K3}:${APP_FOLDER_K3}
      - ${APP_FOLDER_SYSTEM}:${APP_FOLDER_SYSTEM}
      - ${WEBVUE3_PATH_TO_NGINX_CONF}:/etc/nginx/nginx.conf
    networks:
      - karaokenet
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

networks:
  karaokenet:
    driver: bridge

