version: "3.9"
services:

  karaoke-app:
    container_name: karaoke-app
    image: ${DOCKER_REGISTRY}/karaoke-app:${BUILD_VERSION}
    ports:
      - ${APP_PORT_HOST}:${APP_PORT_INSIDE_CONTAINER}
    environment:
      WORK_IN_CONTAINER: 1
    volumes:
      - ${APP_FOLDER_HOST}:${APP_FOLDER_IN_CONTAINER}
      - ${APP_FOLDER_K1}:${APP_FOLDER_K1}
      - ${APP_FOLDER_K2}:${APP_FOLDER_K2}
      - ${APP_FOLDER_K3}:${APP_FOLDER_K3}
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=/dumps
    command: ${APP_JAVA_OPTS} -jar /app.jar
    restart: always

  karaoke-web:
    container_name: karaoke-web
    image: ${DOCKER_REGISTRY}/karaoke-web:${BUILD_VERSION}
    ports:
      - ${WEB_PORT_HOST}:${WEB_PORT_INSIDE_CONTAINER}
    environment:
      WORK_IN_CONTAINER: 1
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=/dumps
    command: ${APP_JAVA_OPTS} -jar /app.jar
    restart: always

  karaoke-webvue:
    container_name: karaoke-webvue
    image: ${DOCKER_REGISTRY}/karaoke-webvue:${BUILD_VERSION}
    ports:
      - "7905:7905"
    depends_on:
      - karaoke-app
    networks:
      - karaokenet
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

networks:
  karaokenet:
    driver: bridge

