version: "3.9"
services:

  karaoke-web:
    container_name: karaoke-web
    image: ${DOCKER_REGISTRY}/karaoke-web:${BUILD_VERSION}
    ports:
      - ${WEB_PORT_HOST}:${WEB_PORT_INSIDE_CONTAINER}
    environment:
      - WORK_ON_SERVER=0
      - WORK_IN_CONTAINER=1
      - STORAGE_FOLDER=${STORAGE_FOLDER}
      - STORAGE_PORT_HOST=${STORAGE_PORT_HOST}
      - STORAGE_PORT_INSIDE_CONTAINER=${STORAGE_PORT_INSIDE_CONTAINER}
      - STORAGE_CONSOLE_PORT_HOST=${STORAGE_CONSOLE_PORT_HOST}
      - STORAGE_CONSOLE_PORT_INSIDE_CONTAINER=${STORAGE_CONSOLE_PORT_INSIDE_CONTAINER}
      - STORAGE_CONTAINER_NAME=${STORAGE_CONTAINER_NAME}
      - STORAGE_KEY=${STORAGE_KEY}
      - STORAGE_SECRET=${STORAGE_SECRET}
      - DB_LOCAL_POSTGRES_USER=${DB_LOCAL_POSTGRES_USER}
      - DB_LOCAL_POSTGRES_PASSWORD=${DB_LOCAL_POSTGRES_PASSWORD}
      - DB_SERVER_POSTGRES_USER=${DB_SERVER_POSTGRES_USER}
      - DB_SERVER_POSTGRES_PASSWORD=${DB_SERVER_POSTGRES_PASSWORD}
#    volumes:
#      - ${WEB_FOLDER_HOST}:${WEB_FOLDER_IN_CONTAINER}
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=/dumps
    command: ${APP_JAVA_OPTS} -jar /app.jar
    restart: always

networks:
  karaokenet:
    external: true # <-- Указываем, что сеть внешняя
