version: "3.9"
services:

  karaoke-web:
    container_name: karaoke-web
    image: svoemestodev/karaoke-web:1
    ports:
      - "8897:7799"
    environment:
      WORK_IN_CONTAINER: 1
    networks:
      - karaokenet
    entrypoint:
      - java
      - -Dfile.encoding=UTF-8
      - -Djava.security.egd=file:/dev/./urandom
    command: -Xmx1048m -jar /app.jar
    restart: always

networks:
  karaokenet:
    driver: bridge

