#!/usr/bin/env bash
# tools/cross-link-density.sh
# Метрика качества LiveDocs: сколько файлов имеют related: ссылки,
# сколько cross-references в среднем, распределение по типам.
#
# Использование:
#   bash tools/cross-link-density.sh              → stdout (human-readable)
#   bash tools/cross-link-density.sh --json       → JSON для CI/automation
#
# Exit code: 0 всегда (это метрика, не CI-gate).

set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# Подсчёт файлов по типу с related:
related_features=$(grep -l "^related:" livedocs/features/*.md 2>/dev/null | grep -v README | wc -l)
related_features_total=$(ls -1 livedocs/features/*.md 2>/dev/null | grep -v README | wc -l)

related_domain=$(grep -l "^related:" livedocs/domain/*.md 2>/dev/null | grep -v README | wc -l)
related_domain_total=$(ls -1 livedocs/domain/*.md 2>/dev/null | grep -v README | wc -l)

related_arc=$(grep -l "^related:" livedocs/architecture/[a-zA-Z]*.md 2>/dev/null | wc -l)
related_arc_total=$(ls -1 livedocs/architecture/[a-zA-Z]*.md 2>/dev/null | wc -l)

related_adr=$(grep -l "^related:" livedocs/architecture/decisions/[0-9]*.md 2>/dev/null | wc -l)
related_adr_total=$(ls -1 livedocs/architecture/decisions/[0-9]*.md 2>/dev/null | wc -l)

# Общее кол-во related: ссылок (считаем строки вида "  - ../..." в frontmatter)
total_related=$(grep -hE "^\s+-\s+\.\./.*\.md$" livedocs/ -r 2>/dev/null | wc -l)

# Всего файлов с related:
total_files_with_related=$(grep -l "^related:" livedocs/**/*.md livedocs/*.md 2>/dev/null | wc -l)

# Всего .md файлов в LiveDocs (с frontmatter eligible для related:)
total_md_files=$(find livedocs -name '*.md' -not -path '*/templates/*' -not -name 'README.md' -not -name 'INDEX.md' -not -name 'INDEX_CARD.md' -not -name 'STATS.md' -not -name 'CHANGELOG.md' -not -path '*/decisions/*' -not -path '*/runbooks/*' -not -path '*/commands/*' | wc -l)

# Среднее кол-во related на файл
avg_related_per_file=0
if [ "$total_files_with_related" -gt 0 ]; then
    avg_related_per_file=$(awk "BEGIN {printf \"%.1f\", $total_related / $total_files_with_related}")
fi

# Распределение по типу ссылки (architecture/domain/features/...)
arch_refs=$(grep -hE "^\s+-\s+\.\./architecture/" livedocs/ -r 2>/dev/null | wc -l)
domain_refs=$(grep -hE "^\s+-\s+\.\./domain/" livedocs/ -r 2>/dev/null | wc -l)
features_refs=$(grep -hE "^\s+-\s+\.\./features/" livedocs/ -r 2>/dev/null | wc -l)
adr_refs=$(grep -hE "^\s+-\s+\.\./architecture/decisions/" livedocs/ -r 2>/dev/null | wc -l)
specs_refs=$(grep -hE "^\s+-\s+\.\./\.\./specs/" livedocs/ -r 2>/dev/null | wc -l)

case "${1:-}" in
    --json)
        cat <<EOF
{
  "files_with_related": $total_files_with_related,
  "total_md_files": $total_md_files,
  "total_related_links": $total_related,
  "avg_related_per_file": $avg_related_per_file,
  "by_layer": {
    "features": {"with_related": $related_features, "total": $related_features_total},
    "domain": {"with_related": $related_domain, "total": $related_domain_total},
    "architecture": {"with_related": $related_arc, "total": $related_arc_total},
    "adr": {"with_related": $related_adr, "total": $related_adr_total}
  },
  "by_link_target": {
    "architecture": $arch_refs,
    "domain": $domain_refs,
    "features": $features_refs,
    "adr": $adr_refs,
    "specs": $specs_refs
  }
}
EOF
        ;;
    "")
        echo "# LiveDocs Cross-link Density"
        echo ""
        echo "_Generated by tools/cross-link-density.sh on $(date +%Y-%m-%d)_"
        echo ""
        echo "## Общая картина"
        echo ""
        echo "| Метрика | Значение |"
        echo "|---------|--------:|"
        echo "| Файлов с \`related:\` | $total_files_with_related / $total_md_files |"
        echo "| Всего cross-link ссылок | $total_related |"
        echo "| Среднее на файл (с related) | $avg_related_per_file |"
        echo ""
        echo "## По слоям (файлов с \`related:\` / всего)"
        echo ""
        echo "| Слой | С related | Всего | Покрытие |"
        echo "|------|----------:|------:|----------:|"
        if [ "$related_features_total" -gt 0 ]; then
            fp=$(awk "BEGIN {printf \"%.0f%%\", $related_features * 100.0 / $related_features_total}")
        else
            fp="—"
        fi
        echo "| features/ | $related_features | $related_features_total | $fp |"

        if [ "$related_domain_total" -gt 0 ]; then
            dp=$(awk "BEGIN {printf \"%.0f%%\", $related_domain * 100.0 / $related_domain_total}")
        else
            dp="—"
        fi
        echo "| domain/ | $related_domain | $related_domain_total | $dp |"

        if [ "$related_arc_total" -gt 0 ]; then
            ap=$(awk "BEGIN {printf \"%.0f%%\", $related_arc * 100.0 / $related_arc_total}")
        else
            ap="—"
        fi
        echo "| architecture/ (topic) | $related_arc | $related_arc_total | $ap |"

        if [ "$related_adr_total" -gt 0 ]; then
            adp=$(awk "BEGIN {printf \"%.0f%%\", $related_adr * 100.0 / $related_adr_total}")
        else
            adp="—"
        fi
        echo "| architecture/decisions/ (ADR) | $related_adr | $related_adr_total | $adp |"
        echo ""
        echo "## По типу ссылки (куда чаще всего ссылаются)"
        echo ""
        echo "| Target | Кол-во ссылок |"
        echo "|--------|--------------:|"
        echo "| \`../architecture/\` | $arch_refs |"
        echo "| \`../domain/\` | $domain_refs |"
        echo "| \`../features/\` | $features_refs |"
        echo "| \`../architecture/decisions/\` | $adr_refs |"
        echo "| \`../../specs/\` (drill-down) | $specs_refs |"
        echo ""
        echo "## Качество"
        echo ""
        echo "Идеально: **100%** файлов имеют \`related:\`."
        echo "Хорошо: ≥80%."
        echo "Плохо: <50% (большинство файлов изолированы — сложно навигировать)."
        ;;
    *)
        echo "Usage: bash $0 [--json]" >&2
        exit 2
        ;;
esac