#!/usr/bin/env bash
# tools/gen-livedocs-index.sh
# Генерирует Mermaid-диаграмму всех LiveDocs в визуальный «карточный» обзор.
# Включает: features, domain (BC), architecture (C4 + topics + ADR), runbooks, commands.
#
# Использование:
#   bash tools/gen-livedocs-index.sh                 → вывод в stdout (Mermaid)
#   bash tools/gen-livedocs-index.sh > livedocs/INDEX_CARD.md
#
# Использует frontmatter (status, slug, type) и slug файла для группировки.

set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

echo "%% LiveDocs Index Card — auto-generated by tools/gen-livedocs-index.sh"
echo "%% Source: livedocs/"
echo "%% Date: $(date +%Y-%m-%d)"
echo ""
echo "graph LR"
echo "    subgraph \"features (\$(ls -1 livedocs/features/*.md 2>/dev/null | grep -v README | wc -l) сводок)\""

# Features
for f in livedocs/features/*.md; do
    [ "$(basename "$f")" = "README.md" ] && continue
    slug=$(awk '/^---$/{c++; next} c==1 && /^slug:/{print $2; exit}' "$f")
    [ -z "$slug" ] && slug=$(basename "$f" .md)
    status=$(awk '/^---$/{c++; next} c==1 && /^status:/{print $2; exit}' "$f")
    # Упростить имя для диаграммы (убрать NNN-slug префикс)
    label="${slug#[0-9]*-}"
    color="green"
    [ "$status" = "Deprecated" ] && color="orange"
    [ "$status" = "Archived" ] && color="gray"
    echo "      F_${slug//[^a-zA-Z0-9_]/_}[\"${label}<br/>${status}\"]:::feature"
done
echo "    end"
echo ""

# Bounded contexts
echo "    subgraph \"domain (\$(ls -1 livedocs/domain/*.md 2>/dev/null | grep -v README | wc -l) BC)\""
for f in livedocs/domain/*.md; do
    [ "$(basename "$f")" = "README.md" ] && continue
    slug=$(awk '/^---$/{c++; next} c==1 && /^slug:/{print $2; exit}' "$f")
    [ -z "$slug" ] && slug=$(basename "$f" .md)
    echo "      D_${slug}[${slug}]:::bc"
done
echo "    end"
echo ""

# Architecture (C4 + topics + ADR)
echo "    subgraph \"architecture\""
echo "      subgraph \"C4\""
for f in livedocs/architecture/L*-*.md; do
    [ -z "$f" ] && continue
    [ ! -f "$f" ] && continue
    slug=$(basename "$f" .md)
    echo "        L_${slug//[^a-zA-Z0-9_]/_}[\"${slug}\"]:::c4"
done
echo "      end"

echo "      subgraph \"topics\""
for f in livedocs/architecture/[a-z]*.md; do
    [ -z "$f" ] && continue
    [ ! -f "$f" ] && continue
    slug=$(basename "$f" .md)
    echo "        T_${slug//[^a-zA-Z0-9_]/_}[\"${slug}\"]:::topic"
done
echo "      end"

echo "      subgraph \"ADR (global)\""
for f in livedocs/architecture/decisions/[0-9][0-9][0-9][0-9]-*.md; do
    [ -z "$f" ] && continue
    [ ! -f "$f" ] && continue
    slug=$(basename "$f" .md)
    echo "        A_${slug//[^a-zA-Z0-9_]/_}[\"${slug}\"]:::adr"
done
echo "      end"

echo "      subgraph \"ADR (local)\""
for f in livedocs/architecture/decisions/local-*.md; do
    [ -z "$f" ] && continue
    [ ! -f "$f" ] && continue
    slug=$(basename "$f" .md)
    echo "        AL_${slug//[^a-zA-Z0-9_]/_}[\"${slug}\"]:::adr"
done
echo "      end"
echo "    end"
echo ""

# Runbooks
echo "    subgraph \"runbooks (\$(ls -1 livedocs/runbooks/*.md 2>/dev/null | grep -v README | wc -l) how-to)\""
for f in livedocs/runbooks/*.md; do
    [ "$(basename "$f")" = "README.md" ] && continue
    slug=$(basename "$f" .md)
    echo "      R_${slug//[^a-zA-Z0-9_]/_}[\"${slug}\"]:::runbook"
done
echo "    end"
echo ""

# Commands
echo "    subgraph \"commands (AI-agent slash-commands)\""
for f in livedocs/commands/*.md; do
    [ "$(basename "$f")" = "README.md" ] && continue
    slug=$(basename "$f" .md)
    echo "      C_${slug//[^a-zA-Z0-9_]/_}[\"${slug}\"]:::command"
done
echo "    end"
echo ""

# Cross-references (simplified): features → domain
echo "    %% Cross-references (simplified):"
for f in livedocs/features/*.md; do
    [ "$(basename "$f")" = "README.md" ] && continue
    f_slug=$(awk '/^---$/{c++; next} c==1 && /^slug:/{print $2; exit}' "$f")
    [ -z "$f_slug" ] && continue
    related=$(awk '/^---$/{c++; next} c>=1 && /^related:/{c=2} c==2 && /^\s*-\s+\.\.\/domain/{print $3; exit}' "$f" 2>/dev/null | head -1)
    if [ -n "$related" ]; then
        related_slug="${related##*/}"
        related_slug="${related_slug%.md}"
        echo "    F_${f_slug//[^a-zA-Z0-9_]/_} -.-> D_${related_slug//[^a-zA-Z0-9_]/_}"
    fi
done

# Classes
echo ""
echo "    classDef feature fill:#c8e6c9,stroke:#388e3c"
echo "    classDef bc fill:#bbdefb,stroke:#1976d2"
echo "    classDef c4 fill:#fff9c4,stroke:#f57f17"
echo "    classDef topic fill:#f8bbd0,stroke:#c2185b"
echo "    classDef adr fill:#d1c4e9,stroke:#512da8"
echo "    classDef runbook fill:#b2dfdb,stroke:#00695c"
echo "    classDef command fill:#ffccbc,stroke:#d84315"