#!/usr/bin/env bash
# tools/gen-livedocs-stats.sh
# Генерирует статистику LiveDocs (количество файлов по типам, статусы фич,
# coverage %, размер). Вывод в stdout (или в файл с перенаправлением).
#
# Использование:
#   bash tools/gen-livedocs-stats.sh                → stdout (Markdown-таблица)
#   bash tools/gen-livedocs-stats.sh livedocs/STATS.md

set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# Счётчики
features_total=$(ls -1 livedocs/features/*.md 2>/dev/null | grep -v README | wc -l)
features_active=$(grep -l "^status: Active" livedocs/features/*.md 2>/dev/null | wc -l)
features_deprecated=$(grep -l "^status: Deprecated" livedocs/features/*.md 2>/dev/null | wc -l)
features_archived=$(grep -l "^status: Archived" livedocs/features/*.md 2>/dev/null | wc -l)

domain_total=$(ls -1 livedocs/domain/*.md 2>/dev/null | grep -v README | wc -l)
domain_with_aggregate=$(grep -l "^## Aggregate Roots" livedocs/domain/*.md 2>/dev/null | wc -l)

c4_count=$(ls -1 livedocs/architecture/L[0-9]-*.md 2>/dev/null | wc -l)
topic_count=$(ls -1 livedocs/architecture/[a-z]*.md 2>/dev/null | wc -l)
adr_global=$(ls -1 livedocs/architecture/decisions/[0-9][0-9][0-9][0-9]-*.md 2>/dev/null | wc -l)
adr_local=$(ls -1 livedocs/architecture/decisions/local-*.md 2>/dev/null | wc -l)

runbooks_total=$(ls -1 livedocs/runbooks/*.md 2>/dev/null | grep -v README | wc -l)
templates_total=$(ls -1 livedocs/templates/*.md 2>/dev/null | grep -v README | wc -l)
commands_total=$(ls -1 livedocs/commands/*.md 2>/dev/null | grep -v README | wc -l)

# Frontmatter
fm_total=$(find livedocs -name '*.md' -not -name 'README.md' -not -name 'INDEX.md' -not -name 'INDEX_CARD.md' -not -path '*/templates/*' -not -path '*/decisions/*' -not -path '*/runbooks/*' -not -path '*/commands/*' -not -path '*/CHANGELOG.md' -exec grep -l "^---$" {} \; 2>/dev/null | wc -l)

# Cross-links (вызываем check-livedocs-cross-links.sh)
cross_links_valid=$(bash tools/check-livedocs-cross-links.sh 2>&1 | grep -oE "All [0-9]+ cross-links valid" | grep -oE "[0-9]+")

# External links
external_links_valid=$(bash tools/check-livedocs-external-links.sh 2>&1 | grep -oE "All [0-9]+ external links valid" | grep -oE "[0-9]+")

# Coverage
coverage_total=$(ls -1 specs/ | grep -E '^[0-9]+-' | wc -l)
coverage_missing=$(bash tools/check-livedocs-coverage.sh 2>&1 | grep -oE "Missing LiveDocs: [0-9]+" | grep -oE "[0-9]+")
coverage_pct=$(awk "BEGIN {printf \"%.1f\", (($coverage_total - $coverage_missing) * 100.0 / $coverage_total)}")

# Size
total_lines=$(find livedocs -name '*.md' -exec cat {} \; 2>/dev/null | wc -l)
total_size=$(find livedocs -name '*.md' -exec wc -c {} \; 2>/dev/null | awk '{sum+=$1} END {print sum}')
total_size_kb=$(awk "BEGIN {printf \"%.0f\", $total_size / 1024}")

# English mirror
en_total=$(find livedocs-en -name '*.md' 2>/dev/null | wc -l)
en_size_kb=$(find livedocs-en -name '*.md' -exec wc -c {} \; 2>/dev/null | awk '{sum+=$1} END {printf "%.0f", sum/1024}')

# Tools
tools_total=$(ls -1 tools/*.sh 2>/dev/null | wc -l)

echo "# LiveDocs Statistics"
echo ""
echo "_Generated by tools/gen-livedocs-stats.sh on $(date +%Y-%m-%d)_"
echo ""

echo "## Coverage"
echo ""
echo "| Metric | Value |"
echo "|--------|------:|"
echo "| Specs in \`specs/\` | $coverage_total |"
echo "| LiveDocs in \`features/\` | $features_total |"
echo "| Coverage | **${coverage_pct}%** ($((coverage_total - coverage_missing)) / $coverage_total) |"
echo ""

echo "## Features"
echo ""
echo "| Status | Count |"
echo "|--------|------:|"
echo "| **Active** | $features_active |"
echo "| Deprecated | $features_deprecated |"
echo "| Archived | $features_archived |"
echo "| **Total** | **$features_total** |"
echo ""

echo "## Domain (Bounded Contexts)"
echo ""
echo "| Metric | Count |"
echo "|--------|------:|"
echo "| Bounded contexts | $domain_total |"
echo "| С \`## Aggregate Roots\` | $domain_with_aggregate |"
echo ""

echo "## Architecture"
echo ""
echo "| Тип | Count |"
echo "|--------|------:|"
echo "| C4 уровни (L1/L2/L3) | $c4_count |"
echo "| Topic-документы | $topic_count |"
echo "| ADR global (0001-NNNN) | $adr_global |"
echo "| ADR local (local-*) | $adr_local |"
echo ""

echo "## Operations"
echo ""
echo "| Слой | Count |"
echo "|--------|------:|"
echo "| Runbooks | $runbooks_total |"
echo "| Templates | $templates_total |"
echo "| Commands (AI-slash) | $commands_total |"
echo "| Tools (*.sh) | $tools_total |"
echo ""

echo "## Validation"
echo ""
echo "| Проверка | Status |"
echo "|---------|--------|"
echo "| Frontmatter (с валидацией) | ${fm_total} файлов |"
echo "| Cross-links valid | $cross_links_valid (0 broken) |"
echo "| External links valid (strict) | $external_links_valid (0 broken) |"
echo "| Markdown structure (depth #26) | 0 issues |"
echo ""

echo "## Size"
echo ""
echo "| Категория | Lines | Size |"
echo "|-----------|------:|-----:|"
echo "| Russian LiveDocs | $total_lines | ${total_size_kb} KB |"
echo "| English mirror | (отдельная метрика) | ${en_size_kb} KB / $en_total files |"
echo ""

echo "## CI Status"
echo ""
echo "| Job | File |"
echo "|-----|------|"
echo "| LiveDocs structure | \`tools/check-livedocs-structure.sh\` (7 checks) |"
echo "| LiveDocs cross-links | \`tools/check-livedocs-cross-links.sh\` |"
echo "| LiveDocs external-links | \`tools/check-livedocs-external-links.sh\` (strict) |"
echo "| Pre-commit hooks | \`.pre-commit-config.yaml\` (4 LiveDocs hooks) |"
echo "| Periodic check | \`.github/workflows/livedocs-external-links-scheduled.yml\` (weekly) |"