server:
  port: 8899
  tomcat:
    connection-timeout: 300000 # 300000 миллисекунд = 5 минут. Установите нужное значение.

spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    cache: false
  main:
    allow-bean-definition-overriding: true

WORK_IN_CONTAINER: 0

work-in-container: ${WORK_IN_CONTAINER}

app:
  max-file-size: 100MB
  max-request-size: 100MB

storage:
  key: ${STORAGE_KEY:minioadmin}
  secret: ${STORAGE_SECRET:minioadmin}
  folder: ${STORAGE_FOLDER:karaoke}
  port-host: ${STORAGE_PORT_HOST:9000}
  port-inside-container: ${STORAGE_PORT_INSIDE_CONTAINER:9000}
  container-name: ${STORAGE_CONTAINER_NAME:karaoke-storage}
  console:
    port-host: ${STORAGE_CONSOLE_PORT_HOST:9001}
    port-inside-container: ${STORAGE_CONSOLE_PORT_INSIDE_CONTAINER:9001}

#logging:
#  level:
#    org.springframework.security: DEBUG

#cors:
#  allowed-origins: "http://localhost:3000,http://127.0.0.1:3000,http://localhost:7906"

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG