server:
  port: 8899
  tomcat:
    connection-timeout: 300000 # 300000 миллисекунд = 5 минут. Установите нужное значение.

spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  main:
    allow-bean-definition-overriding: true

WORK_IN_CONTAINER: 0

work-in-container: ${WORK_IN_CONTAINER}